{
  "formatVersion": "1.1",
  "component": {
    "group": "com.aqrlei.lib",
    "module": "litenet-transformer-moshi",
    "version": "0.0.1-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "kgazplyblfczxpfp4pyzlalbya"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "litenet-transformer-moshi-0.0.1-alpha01.aar",
          "url": "litenet-transformer-moshi-0.0.1-alpha01.aar",
          "size": 18818,
          "sha512": "4e7a2ffe04d49ac37db0a122e6406862779559ae4100762a0f61e52a65b3105be828ff3ec18fb8572ba4765cd6ea8a958205c0b1ecf6bfed595e8edaf095151b",
          "sha256": "27948f0d7749c1997cf2b62c6b9d16c65d6b936a043043b5c3b1aff5db1dc103",
          "sha1": "1c0ceb6aeb725f3052c1f8bc770e3fd6c5522423",
          "md5": "fd67329fd99eccae7df9bde2db6ef627"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.4.1"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin-codegen",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "com.aqrlei.lib",
          "module": "litenet",
          "version": {
            "requires": "1.0.2-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "litenet-transformer-moshi-0.0.1-alpha01.aar",
          "url": "litenet-transformer-moshi-0.0.1-alpha01.aar",
          "size": 18818,
          "sha512": "4e7a2ffe04d49ac37db0a122e6406862779559ae4100762a0f61e52a65b3105be828ff3ec18fb8572ba4765cd6ea8a958205c0b1ecf6bfed595e8edaf095151b",
          "sha256": "27948f0d7749c1997cf2b62c6b9d16c65d6b936a043043b5c3b1aff5db1dc103",
          "sha1": "1c0ceb6aeb725f3052c1f8bc770e3fd6c5522423",
          "md5": "fd67329fd99eccae7df9bde2db6ef627"
        }
      ]
    }
  ]
}
